server:
  port: 2020

spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        metadata:
          gray: true
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include:
          - service-registry